### ISSUE TITLE
Benchmark results/charts in README.

### ISSUE THREAD

**Issue by naushadh** [composewell/streaming-benchmarks#1]
Just came across `streamly` and am super fascinated. Love that there's a repo with many of the popular streaming libs pit head to head. Unfortunately I cannot find any benchmark results. If you have them handy, could you please upload them to this repo and show it off in the README?

**Comment by harendra-kumar** [comment]
I have quite a few changes in the benchmarks code pending to be committed in my workspace. I will clean it up soon and upload hopefully along with results.

**Comment by harendra-kumar** [comment]
@naushadh I have updated the repo. Lot of changes. Take a look at the new README. I have the charting code as well in the local repo, will upload that soon. Till then you can try playing with the benchmarks. Let me know if you trip over something or if something is not easily understood.

**Comment by harendra-kumar** [comment]
Readme has the charts now, closing this issue.

**Comment by naushadh** [comment]
Thank you so much!
