### ISSUE TITLE
Use unfoldrM or equivalent for drinkery

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/streaming-benchmarks#10]
@fumieval I have moved away from generating the stream from a list, instead we generate it using `unfoldrM`(monadic unfoldr) now. I could adapt all other libraries to use `unfoldrM` or equivalent but could not find one for `drinkery`. Can you help me do that so that we can have a fair comparison across all libraries. `drinkery` seems to be equal or faster than other mainstream libraries so I do not mean to keep it out.

**Comment by fumieval** [comment]
I've just uploaded drinkery-0.4 with a new function similar to `unfoldrM`. https://github.com/composewell/streaming-benchmarks/pull/11

It might take some time to get hackage.fpcomplete.com synchronised.

**Comment by harendra-kumar** [comment]
Great! I will try rerunning the benchmarks and see where it stands after this change.

**Comment by harendra-kumar** [comment]
Fixed by #11
