### ISSUE TITLE
Could this repo be a part of haskell-perf?

### ISSUE THREAD

**Issue by qrilka** [composewell/streaming-benchmarks#9]
https://github.com/haskell-perf looks to be an useful source of information about haskell performance, probably it could make sense to have these benchmarks as a project of that performance org?

**Comment by ocramz** [comment]
@harendra-kumar I agree with @qrilka :) haskell-perf is the perfect place for this.

**Comment by harendra-kumar** [comment]
This is associated with streamly development at Composewell, this is all about what we are doing right now and therefore I would like to keep it here for now. The location of the package should not be a hindrance to anything I guess. The code and results are completely objective and unbiased (the readme is a bit streamly centric though, and purposely so) and we are committed to keep it so. It supports almost all notable libraries and we encourage people to add more freely, notable or not. Thanks for the suggestion, I was not aware of that repo and will think of revisiting this later.

**Comment by harendra-kumar** [comment]
closing this for now.
